name: watchlist
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  sqflite: ^2.0.0+3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.2
  cached_network_image: ^3.0.0
  flutter_rating_bar: ^4.0.0
  flutter_bloc: ^8.0.0
  rxdart: ^0.27.1
  dartz: ^0.10.0-nullsafety.2
  
  movie:
    path: ../movie

  series:
    path: ../series

  about:
    path: ../about

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.0.8
  bloc_test: ^9.0.0
  build_runner: ^2.0.4

flutter:

  uses-material-design: true
